language: python
python:
- '2.7'
- pypy

env:
  global:
    - CORTICAL_API_KEY="dummy_api_key"

install:
 - pip install pytest
 - python setup.py install

script:
 - py.test --cov cortipy

after_success:
 - pip install python-coveralls
 - coveralls
